;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Journal.Character.Boss.Age",NewTagName="Journal.Character.Fetard.Age")
+GameplayTagRedirects=(OldTagName="Journal.Character.Boss.Background",NewTagName="Journal.Character.Fetard.Background")
+GameplayTagRedirects=(OldTagName="Journal.Character.Boss.Name",NewTagName="Journal.Character.Fetard.Name")
+GameplayTagRedirects=(OldTagName="Journal.Character.Boss",NewTagName="Journal.Character.Fetard")
+GameplayTagList=(Tag="Journal.Character.Fetard.Age",DevComment="")
+GameplayTagList=(Tag="Journal.Character.Fetard.Background",DevComment="")
+GameplayTagList=(Tag="Journal.Character.Fetard.DrinkRequested",DevComment="")
+GameplayTagList=(Tag="Journal.Character.Fetard.Info2",DevComment="")
+GameplayTagList=(Tag="Journal.Character.Fetard.Name",DevComment="")
+GameplayTagList=(Tag="Journal.Character.Mafia.Age",DevComment="")
+GameplayTagList=(Tag="Journal.Character.Mafia.Background",DevComment="")
+GameplayTagList=(Tag="Journal.Character.Mafia.DrinkRequested",DevComment="")
+GameplayTagList=(Tag="Journal.Character.Mafia.Info2",DevComment="")
+GameplayTagList=(Tag="Journal.Character.Mafia.Name",DevComment="")
+GameplayTagList=(Tag="Journal.Character.OldMan",DevComment="")
+GameplayTagList=(Tag="Journal.Character.OldMan.Age",DevComment="")
+GameplayTagList=(Tag="Journal.Character.OldMan.Background",DevComment="")
+GameplayTagList=(Tag="Journal.Character.OldMan.DrinkRequested",DevComment="")
+GameplayTagList=(Tag="Journal.Character.OldMan.Info2",DevComment="")
+GameplayTagList=(Tag="Journal.Character.OldMan.Name",DevComment="")
+GameplayTagList=(Tag="Journal.Character.Woman.Age",DevComment="")
+GameplayTagList=(Tag="Journal.Character.Woman.Background",DevComment="")
+GameplayTagList=(Tag="Journal.Character.Woman.DrinkRequested",DevComment="")
+GameplayTagList=(Tag="Journal.Character.Woman.Info2",DevComment="")
+GameplayTagList=(Tag="Journal.Character.Woman.Name",DevComment="")
+GameplayTagList=(Tag="Quest.Fetard.WinMinigame",DevComment="")
+GameplayTagList=(Tag="Quest.Mafia.GetDrink",DevComment="")
+GameplayTagList=(Tag="Quest.OldMan.GetBeer",DevComment="")
+GameplayTagList=(Tag="Quest.OldMan.GetDrink",DevComment="")

